### PR TITLE
Basic requestor list display

### PR DESCRIPTION
**Pull request by dix4724**
-added db creds to config.php in capstone_includes(outside repo) -connect to db, query sm_requestors table
-form contains records in table
- container styles to show viewer list and hide my account divs

### CODE REVIEW

**Comment by xancara** [comment]
@dix4724 It looks like you have the basic idea down for this but we can turn the drop down into simple buttons.

It'll be easier for you to deal with the updates themselves if you have them simply identify and build each action into the row:

Example: 
```html
<a href="/php/process_myviewers.php?cmd=togglewhitelist&viewer=Viewer1"><img src="path\to\image.png" /></a>
<a href="/php/process_myviewers.php?cmd=toggleban&viewer=Viewer1"><img src="path\to\image.png" /></a>
```

This way you can take care of the processing all in once place and simply pass all of your commands back to that specific processing page. This will help keep things organized as well. 

Additionally, We can add some functions into functions.php to help call over to the SMR tables instead of writing a new connection on each page. This should be a globally accessible DB user processing these requests on all users individual DBs so we can work on that. 

For now, let's go ahead and make a change to your select list to make them images or anchors for the time being that will call to that processing page. Go ahead and commit that, and I'll accept the PR. I'll also look to write the function for calling to all of the SMR users tables and get a commit in after your PR is resolved.

I think I will also add a $dbPrefix and $smrPrefix in the config.php so we can reliably call to any of the tables with more simple language.

**Comment by dix4724** [comment]
Pushed a commit with those changes (I think), hopefully this worked - added additional comments on the commit itself.

Let me know if this works for now!

**Comment by dix4724** [comment]
This most recent commit incorporates some additional comments and feedback from yourself and Jenn that I missed before the previous commit. Added a global function to update SMR tables along those lines. Also built out process_myviewers.php so that updates seem to be working properly now for the most part.

**Comment by xancara** [comment]
Looks fine for testing purposes. Remember that we will need this to be dynamic at some point so all of the places we are hard coding the user will need to be changed to the session => UserInfo => twitch handle or something of the sort (once we get that info from the provisioned user). 

Using the hardcoded value will be fine for our purposes until we get further along.

**Pull request merged**
